version: "3"
services:
  fe-1:
    image: selectdb/doris.fe-ubuntu:2.1.2
    hostname: fe-1
    container_name: fe-1
    environment:
     - FE_SERVERS=fe1:172.25.2.3:9010,fe2:172.25.2.4:9010,fe3:172.25.2.5:9010
     - FE_ID=1
    volumes:
     - /data/fe/doris-meta/:/opt/apache-doris/fe/doris-meta/
     - /data/fe/log/:/opt/apache-doris/fe/log/
    network_mode: host
  be-1:
    image: selectdb/doris.be-ubuntu:2.1.2
    hostname: be-1
    container_name: be-1
    environment:
     - FE_SERVERS=fe1:172.25.2.3:9010,fe2:172.25.2.4:9010,fe3:172.25.2.5:9010
     - BE_ADDR=172.25.2.3:9050
    volumes:
     - /data/be/storage/:/opt/apache-doris/be/storage/
     - /data/be/script/:/docker-entrypoint-initdb.d/
    depends_on:
      - fe-1
    network_mode: host