services:
  loadbalancer:
    hostname: loadbalancer
    container_name: loadbalancer
    build:
      context: .
      dockerfile: Dockerfile
    runtime: sysbox-runc
    networks:
      k3s_network:
        ipv4_address: 172.25.1.2
  master-1:
    hostname: master-1
    container_name: master-1
    build:
      context: .
      dockerfile: Dockerfile
    runtime: sysbox-runc
    networks:
      k3s_network:
        ipv4_address: 172.25.1.3
  master-2:
    hostname: master-2
    container_name: master-2
    build:
      context: .
      dockerfile: Dockerfile
    runtime: sysbox-runc
    networks:
      k3s_network:
        ipv4_address: 172.25.1.4
  master-3:
    hostname: master-3
    container_name: master-3
    build:
      context: .
      dockerfile: Dockerfile
    runtime: sysbox-runc
    networks:
      k3s_network:
        ipv4_address: 172.25.1.5
  worker-1:
    hostname: worker-1
    container_name: worker-1
    build:
      context: .
      dockerfile: Dockerfile
    runtime: sysbox-runc
    networks:
      k3s_network:
        ipv4_address: 172.25.1.6
  worker-2:
    hostname: worker-2
    container_name: worker-2
    build:
      context: .
      dockerfile: Dockerfile
    runtime: sysbox-runc
    networks:
      k3s_network:
        ipv4_address: 172.25.1.7
  worker-3:
    hostname: worker-3
    container_name: worker-3
    build:
      context: .
      dockerfile: Dockerfile
    runtime: sysbox-runc
    networks:
      k3s_network:
        ipv4_address: 172.25.1.8
networks:
  k3s_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.25.1.0/24
         gateway: 172.25.1.1