trino:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: "{{ env_var('TRINO_USER') }}"
      host: "{ { env_var('TRINO_HOST') } }"
      port: "{{ env_var('TRINO_PORT') }}"
      http_scheme: http
      database: lakehouse
      schema: jaffle_shop
