additionalCatalogs:
  lakehouse: |
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore.metastore.svc.cluster.local:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=password
    iceberg.register-table-procedure.enabled=true
    iceberg.unique-table-location=true
    iceberg.hive-catalog-name=minio
  minio: |
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore.metastore.svc.cluster.local:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio.minio.svc.cluster.local:9000
    hive.s3.aws-access-key=admin
    hive.s3.aws-secret-key=password
    hive.metastore.thrift.client.connect-timeout=3m
    hive.metastore.thrift.client.read-timeout=3m
    hive.s3.connect-timeout=3m
    hive.s3.socket-timeout=3m
    hive.non-managed-table-writes-enabled=true
    hive.storage-format=ORC
    hive.partition-projection-enabled=true
auth:
  passwordAuth: "admin:$2y$10$32rtjQj8dPi4RNZ9pIcVVu6S5q8tidEY5giLaGr.yzoOHEQlTnC2C\ntest:$2y$10$AsfYDEb0puMrAn8njHwDoeB2ADKXs0Uk9A0qiimbgRXk8dYZF0Brq"
server:
  config:
    authenticationType: "PASSWORD"
  workerExtraConfig: |-
    internal-communication.https.required=true
    internal-communication.shared-secret=test
    http-server.https.enabled=true
    discovery.uri=https://trino:8443
    http-server.authentication.type=PASSWORD
  coordinatorExtraConfig: |-
    internal-communication.https.required=true
    internal-communication.shared-secret=test
    # discovery.uri=https://trino:8443
    http-server.process-forwarded=true
    http-server.https.enabled=true
    http-server.https.port=8443
    http-server.authentication.type=PASSWORD

accessControl:
  type: configmap
  refreshPeriod: 60s
  # Rules file is mounted to /etc/trino/access-control
  configFile: "rules.json"
  rules:
    rules.json: |-
      {
        "catalogs": [
          {
            "user": "admin",
            "catalog": "(lakehouse|minio)",
            "allow": "all"
          },
          {
           "user": "test",
           "catalog": "(lakehouse|minio)",
           "allow": "read-only"
         }
        ]
      }
coordinator:
  additionalExposedPorts:
    https:
      servicePort: 8443
      name: https
      port: 8443
      protocol: TCP
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: trino.ggg.com.vn
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: trino-tls
      hosts:
        - trino.ggg.com.vn
