apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: {{ template "kube-doris.name" . }}-operator-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ template "kube-doris.name" . }}-operator
    app.kubernetes.io/part-of: {{ template "kube-doris.name" . }}-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template "kube-doris.name" . }}-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-doris.name" . }}-operator
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-doris.name" . }}-operator
    namespace: {{ template "operator.namespace" . }}
