apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-doris-operator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ template "kube-doris.name" . }}-operator
    app.kubernetes.io/part-of: {{ template "kube-doris.name" . }}-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ template  "operator.serviceAccountName" . }}
  namespace: {{ template  "operator.namespace" . }}
