apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: connect-configs
  namespace: kafka
  labels:
    strimzi.io/cluster: tgs-integration-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: compact
