apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
    - ssh:
        address: 10.4.165.45
        user: k0s
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller
    - ssh:
        address: 10.4.165.207
        user: k0s
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller
    - ssh:
        address: 10.4.165.154
        user: k0s
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: controller
    - ssh:
        address: 10.4.165.199
        user: k0s
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 10.4.165.114
        user: k0s
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
    - ssh:
        address: 10.4.165.245
        user: k0s
        port: 22
        keyPath: ~/.ssh/id_rsa
      role: worker
  k0s:
    version: v1.30.0+k0s.0
    config:
      spec:
        api:
          externalAddress: 10.4.165.85
          sans:
            - 10.4.165.85
